language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit

matrix:
  fast_finish: true